spring:
  application:
    name: servicio-reservas   
server:    
  port: 10000
eureka:        
  client:
    #No es necesario que la aplicación cliente se registre en Eureka
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
